# This workflow builds and deploys a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows manual triggering from the Actions tab
  workflow_dispatch:

# Set necessary permissions for deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Prevents multiple concurrent deployments, but allows running in-progress deployments to complete
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Specify Ruby version
          bundler-cache: true # Cache gems for faster builds
          cache-version: 0 # Change if you need to invalidate the cache

      # Step 3: Install Jekyll dependencies (Fix for missing dependencies)
      - name: Install Jekyll and dependencies
        run: |
          gem install jekyll bundler
          bundle install

      # Step 4: Setup GitHub Pages
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      # Step 5: Build Jekyll site
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      # Step 6: Upload the built site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
